### ISSUE TITLE
Replace AWS Billing and GCE Billing modules with revamped bill Calculator code.

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#59] opened 2020-03-25 22:24 UTC
Maria Acosta has revamped the Bill Calculator code that runs on hepcsvc01 to be much better structured
and to have a unified module that does both the analysis and the alarms.
The way this is structured, it should be a near drop-in replacement for the respective AWS and GCE billing 
modules that are in the decision engine modules currently.. all that should be necessary is a bit of
integration and testing.

Once Maria releases the pip module we will post that info to this ticket.
The changes need to be made at least on the AWS side because the location of some of the accounting buckets changed as of mid-July 
and the decision engine as currently operating has no visibility into the R+D account expenditures.

**Comment by DmitryLitvintsev** [comment] 2020-04-01 00:29
And, while we are at it, add a detection to this code so that it will detect if no new usage data has been detected in the AWS spreadsheets for some amount of time.

**Comment by DmitryLitvintsev** [comment] 2020-04-01 00:30
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/181

**Comment by hyunwoo18** [comment] 2020-07-01 22:49
I started working on this:
Some details are:

- I am beginning with AWS module (AWS/sources/BillingInfo.py) first.

- I just copied	AWSBillAnalysis.py from Maria's new code into my VM:/usr/lib/python2.7/.../AWS/sources/.
   because it turns out Maria	has not built a pip module nor rpm package yet.
 (I also had to copy graphite.py to clear an error).

- And I just import AWSBillCalculator from AWSBillAnalysis.py
   and use AWSBillCalculator in the same	way as hcf-bill-calculator (Maria's executable)
  uses it.

- For this to work, I created the same environment as hepcsvc01	(where Maria's code runs)
  manually for now in my VM:
  /etc/cloud-security/awsbilling/credentials (with access keys of Billing AWS user)
  /etc/hepcloud/config.d/AWS.yaml

- Now, finally the testing begins:
  It almost works, i.e.	the code proceeds as far as to invoking	AWS APIs
  but for a reason that	will be	investigated further,
  s3.download_file call	fails the error	code 13	(Permission Denied).
  It looks like	S3 bucket for the billing files	has some ACL or	so.

- After	this test, I will proceed to GCE/sources/GCEBillingInfo.py

**Comment by hyunwoo18** [comment] 2020-07-07 20:00
I basically conducted a test to update the channel:AWSbilling -> source:BillingInfo -> decisionengine_modules.AWS.sources.BillingInfo.py
to used the new class AWSBillCalculator(object): from AWSBillAnalysis.py
and eventually confirmed that 'dst_dir_for_s3_files': '/var/lib/decisionengine/awsfiles'
is populated with the csv.zip  files.

At this point, I will pause this work on AWSbilling, and will move to GCEbilling
because Maria's code is writtin in Python3, a full testing in python3 DE environment
will not be possible before GWMS python3 is available.

I talked with Maria and	she says she will build pip or rpm by next week.

**Comment by hyunwoo18** [comment] 2020-07-16 00:52
Today, I followed a similar set of steps as last week's AWS to replace the current class GCEBillCalculator
in GCEBillingInfo.py with a new one from Maria's new GCEBillAnalysis.py.

Here are some details that I had to conduct to make that happen:

```
1. Copied /etc/hepcloud/config.d/GCE.yaml from hepcsvc01

2. Created a new subdirectory called POC under /var/lib/decisionengine/gcefiles/

3. I didn't have to touch anything regarding /home/decisionengine/.config/gcloud/

4. cp AWS/sources/graphite.py GCE/sources/
     This step will not be necessary later when I install Maria's package via pip
     (She told me that she had completed packaging yesterday)

5. emacs GCEBillAnalysis.py
     import configparser
     to
     import ConfigParser
    This step will not be necessary later when we upgrade to Python3

6. emacs GCEBillingInfo.py to add
     import yaml
     This will change when I adopt the new configuration system (jsonette)
```

After all these changes, I could confirm that this new source downloaded csv files in /var/lib/decisionengine/gcefiles/POC

One change that must be done later is, Maria's logic in acquire method in GCEBillingInfo.py
assumes the possibility of multiple GCP accounts whereas the current code does not.

So, Maria's code 
```
  def acquire(self):
        GCEconstants = "/etc/hepcloud/config.d/GCE.yaml"
        with open(GCEconstants, 'r') as stream:
            config = yaml.safe_load(stream)
        globalConf = config['global']
        snowConf   = config['snow']

        for constantsDict in config['accounts']:
            account = constantsDict['accountName']

            try:
............
                calculator = GCEBillCalculator( account, globalConf, constantsDict, self.logger )
                lastStartDateBilledConsideredDatetime, CorrectedBillSummaryDict = calculator.CalculateBill()
            except Exception as detail:
                self.logger.error(detail)

            return { PRODUCES[0]: pd.DataFrame( [ CorrectedBillSummaryDict ] ) }
```
works as GCE.yaml currently has just one account but I will need to move the return statement later.

**Comment by hyunwoo18** [comment] 2020-07-21 18:52
I found one part of Maria's code needs to be updated and opened an issue in her gitlab repo.
There, I described what needs to be updated and how in details.
I might end up working on that.
I also asked Kyle about the current status of his work on jsonette.
This is because Maria's code is loading configuration values from a YAML and
I could change this to the current configuration system of DE, but as we are expecting jsonette to come soon,
I decided to wait until then and use it.

**Comment by hyunwoo18** [comment] 2020-08-06 18:29
Maria built a new pip package the other day and Steve and I conducted a real environment test today in his VM
and we discovered that a few more changes were necessary.
I updated Maria's code (AWSBillAnalysis.py GCEBillAnalysis.py) one more time and asked her to review them.
When she is okay with these, she will have to build a new package.
In the meantime, I will  update my branch for decisionengine_modules.

**Comment by StevenCTimm** [comment] 2020-08-06 21:26
The current state of the new modules is that they are up and running stably but there are some differences in the value of the output data from the old to the new.  In particular it appears that in Pandas 1.0 the columns that don't have any current entries in the billing .csv files don't get populated at all, and the datablock doesn't get dumped out with columns in alphabetical order.  I continue to look at the numbers and see what is different.

Also the RnD account continues to show zero expenditures for the year (as the old code also did).. that is a function that somehow we are pointing at the wrong bucket location.  We have to figure out how to fix that.  (the hepcsvc01 installation of Maria's code doesn't have this problem).  There is a field called bucketBillingName that needs to be set, I think.

**Comment by StevenCTimm** [comment] 2020-08-06 21:27
The Google balance also comes out quite differently--we are going to have to work on this a bit more.
Note that the input constants are the same.

**Comment by hyunwoo18** [comment] 2020-08-07 20:57
Let me summarize the current status before we put this issue on hold

I just briefly chatted with Steve about the following points:
Steve installed this new Maria's billing package in VM
and has been comparing the new results from this and the current results from cmsde01
and as he mentioned above, Steve is seeing some discrepancies between these 2 results.

So,
1. we should ask Maria or ourselves whether or not she or we in general made sure that her new billing calculator produces the same results as the previous one by Sasha/Krista.

2. if this new and old results are different, do we know which is closer to or identical to the true value from AWS?

My scope of work on this issue was/is just to make sure that Maria's package is functional within the DE framework. I tested this in my own environment and Steve also tested this and we know that this goal has
been fulfilled.

So, Steve will continue investigation into these questions and I will just wrap up the task of merging my branch into the master. Note my branch has already been reviewed by Pat two weeks ago.

After this, I will move on to the issue 63 and my group duty.

**Comment by StevenCTimm** [comment] 2020-08-10 01:45
I have investigated and the new code running on fermicloud117 is giving the correct answer, and the old code is not.
We should proceed with getting this code merged into the master
One point that still has to be dealt with is that the changes that we made to Maria's module broke it in its
original location.  Since we are not running it in the same working directory as its modules sit, we have to add 
bill_calculator_hep. to the import statements--and that breaks the dependencies if you do run it in the same directory.

**Comment by hyunwoo18** [comment] 2020-08-10 02:16
Thanks for your investigation Steve.
Like I communicated with you in emails, Maria will from now on build 2 versions, one for her standalone use in hepcsvc01
and one for our library use for DE.
Tomorrow I will wrap up this ticket.

**Comment by hyunwoo18** [comment] 2020-08-27 16:54
I updated requirements.txt and build/scripts/utils.sh to include 
pip3 install --index-url https://test.pypi.org/simple --no-deps bill-calculator-hep-mapsacosta==0.0.5
and pushed to https://github.com/hyunwoo18/decisionengine_modules.git
which triggered the unit test.
This is failing currently only because I believe Maria did not build this package properly.
I will talk with her this afternoon to sort this out.

**Closed** 2020-09-03 20:49 UTC
Labels: onmachine_patch, operations
