### ISSUE TITLE
GCE channel goes OFFLINE on a timeout

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#69] opened 2020-03-25 23:44 UTC
Gce channel died on a timeout

2018-12-02 17:26:25,584 - decision_engine - TaskManager - GceOccupancy - ERROR - error running source GceOccupancy <class 'ssl.SSLError'> ('The read operation timed out',)

After one timeout the channel is set offline, this seems rather extreme

**Comment by DmitryLitvintsev** [comment] 2020-04-01 00:59
Related to #70

**Comment by DmitryLitvintsev** [comment] 2020-04-01 01:00
Imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/120

**Comment by hyunwoo18** [comment] 2020-06-03 19:46
I am looking at this issue in order to find my next ticket (as I finished #198)
and as you said, I also looked at #70.
It looks like the solution from 70 (retrying) might have already taken care of this one too.
What do you think?

**Comment by DmitryLitvintsev** [comment] 2020-06-03 19:49
yes, same approach may work here.

**Comment by hyunwoo18** [comment] 2020-06-03 19:52
This problem was reported in the December of 2018
and we now have the new code
```
    def acquire(self):
        tries = 0
        while True:
            try:
                return self._acquire()
            except RuntimeError:
                raise
            except Exception as e:
                if tries < self.max_retries:
                    tries += 1
                    time.sleep(self.retry_timeout)
                    continue
                else:
                    raise RuntimeError(str(e))
```
So, I think with this new code in place, this old problem might be already taken care of.
I think.

**Comment by DmitryLitvintsev** [comment] 2020-06-03 19:54
;) yeah. Need to get confirmation from Steve

**Comment by hyunwoo18** [comment] 2020-06-03 19:56
I don't think Steve is receiving emails from this ticket.
I will tell him now to look at today's comments.

**Comment by StevenCTimm** [comment] 2020-06-03 20:04
When was this code added to GceOccupancy.py?  has it been there a long time or did you just add it recently?  Is it in the version we are running in production now?

**Comment by hyunwoo18** [comment] 2020-06-03 21:16
I thought the code that I showed above was from Shreyas' work as mentioned in 70
but this work there was for NERSC, not GCE.
So, I am not sure when this code was added in GCE/sources/GceOccupancy.py.
Need more investigation.

**Comment by StevenCTimm** [comment] 2020-06-03 21:27
GCE doesn't go offline very often.. it will be very hard to reproduce this in the wild.

**Comment by StevenCTimm** [comment] 2020-06-04 14:31
I checked the 0.3 branch that we were running in production and the above code snippet was in there.  So this fix has been in a long time.  But up until now there has been no max_retries 
defined in the configuration file so the code path has never been activated.  I will try to add a max_retries to the configuration file and see if that has any effect. But as I said above, GCE failures are rare to start with and it is unlikely that even if we manage to catch the failure in the wild, that
we will notice what happened.  This would be a good thing to unit test if there's not already a unit test for it.

**Comment by StevenCTimm** [comment] 2020-06-04 21:55
Discussion in development meeting today was that Hyunwoo will change this code to use the same decorator the other routines are using.  In the meantime I have added a retry configuration option to the existing code and will run in that state.

**Comment by hyunwoo18** [comment] 2020-06-09 22:14
I updated the code and created a new review request
https://fermicloud140.fnal.gov/reviews/r/150/

**Comment by StevenCTimm** [comment] 2020-06-12 15:33
This code is now in the 1.2.1 branch rpm and running on fermicloud117. 
We will never know for sure if it works until such time as GCE goes down again.
I suggest we close this ticket and open a new one if there are further issues.

**Closed** 2020-07-02 19:53 UTC
Labels: operations
