### ISSUE TITLE
AWS Occupancy source errors out when AWS is down.

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#60] opened 2020-03-25 22:24 UTC
'<pre>
2019-10-22 13:33:31,462 - root - TaskManager - 88220 - AWSOccupancy - ERROR - Exception running source AWSOccupancy
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 279, in run_source
    data = src.worker.acquire()
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/AWS/sources/AWSOccupancyWithSourceProxy.py", line 161, in acquire
    instances = occcupancy.get_ec2_instances()
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/AWS/sources/AWSOccupancyWithSourceProxy.py", line 80, in get_ec2_instances
    for instance in instances:
  File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)

  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
</pre>
----------

This is from AWSOccupancyWithSourceProxy.py 

It should be noted that the BillingInfo.py  (in AWSBilling channel) also makes an error 
even though it goes offline.  It produces an empty billing data block which then the logic engine
errors out on because it is looking for data in the row of the aws_billing_info 
data block which is not there
<pre>
IndexError: single positional indexer is out-of-bounds
2019-10-22 16:47:38,472 - root - TaskManager - 125019 - MainThread - ERROR - error in decision cycle(logic engine)
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bound
</pre>
Ditto the AWS_Burn_Rate source proxy also fails because it's trying to fetch a blank data block.

-----------------------------

this is the first time that AWS us-east was down and so this was the first time we ever saw these data block errors.

We need to make sure that these errors don't cause the fail of the whole DE, which at one point when we
tried to restart it, it did because of missing data blocks.
Also esp. for billing if there is a failure we need to know and just keep the old data block as good, because it only changes at most every 6 hours.

**Comment by DmitryLitvintsev** [comment] 2020-04-01 00:28
These errors are now happening with increased frequency.. the AWS_Calculations_with_source_proxy channel goes offline on average of once or twice a week, nowadays most likely in the AWS_Burn_Rate
transform.  There is a source upstream of that which fails, but catches the exemption and returns a null datablock, and the transform then fails because it is looking for a key which is not in the null datablock.

**Comment by DmitryLitvintsev** [comment] 2020-04-01 00:28
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/182

**Comment by hyunwoo18** [comment] 2020-06-04 14:50
I am thinking of trying this ticket too.

**Comment by hyunwoo18** [comment] 2020-06-06 01:58
I have been trying to understand Dmitry's descriptions of the problems in the two channels
and here is my understanding of the obvious similarity in the failures:

1. channel: AWSbilling
Problem is
```
(sources: BillingInfo) fails to contact AWS and then produces "empty billing data block"
(logicengines: logicengine1) tries to access data in the row of the aws_billing_info data block which is not there.

Dmitry's suggestion for solution:
for billing if there is a failure we need to know and just keep the old data block as good, because it only changes at most every 6 hours.
```

2. channel: AWS_Calculations_with_source_proxy
Problem is
```
(sources AWSOccupancyWithSourceProxy) fails to contact AWS and then produces "null data block"
(transforms:AWS_Burn_Rate)  fails because it's trying to fetch a blank data block.
```

So, I need ask questions here:
what kind of solution needs to be implemented here?
Namely, it appears to me that the biggest problem here is the fact that failure to access AWS results in "null data block" which triggers a domino failures of consequent modules in a channel.

If the code is updated in such a way to	at least prevent the data block from becoming null by forbidding the modules (mostly source modules) from overriding the existing non-null datablock when it fails to access AWS and then in the next round try again and so on,
will this be considered a possible solution?

**Comment by StevenCTimm** [comment] 2020-06-09 20:33
I think in the long term this needs to be addressed in the framework error handling work that is scheduled.  The idea of "keeping the old data block" is a good idea but I am not sure if a module can even do this on its own.. can it?  

what you propose " forbidding the modules (mostly source modules) from overriding the existing non-null datablock when it fails to access AWS" is a nice idea if it can be done.

Also note issue #240 which I just opened, in which in the python3 branch AWSbilling is failing all the time (but still showing STEADY)

**Comment by hyunwoo18** [comment] 2020-06-12 04:23
I inspected decisionengine_modules/AWS/sources/AWSOccupancyWithSourceProxy.py 
focusing on the following structure:

```
class OccupancyData(object):
class OccupancyForRegion(object):
    def get_ec2_instances(self):
    def capacity(self, instances):

class AWSOccupancy(SourceProxy.SourceProxy):
    def acquire(self):

        for k in account_conf:
            self.account_dict = account_conf[k].to_dict()

        occupancy_data = []

        for    account in self.account_dict:
            for region in self.account_dict[account]:

                occcupancy = OccupancyForRegion( region, profile_name=account )

		instances = occcupancy.get_ec2_instances()

		if instances:
                    data = occcupancy.capacity( instances )
                    if data:
                        occupancy_data += data

        oc_list = [ i.data for i in occupancy_data ]

        return { PRODUCES[0]: pd.DataFrame(oc_list) }
```

My question here is,

- if I update the code such that
```
                occcupancy = OccupancyForRegion( region, profile_name=account )
or
  		instances = occcupancy.get_ec2_instances()

inside  class AWSOccupancy(SourceProxy.SourceProxy):     def acquire(self):
```
catches exceptions due to
```
EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
```
error as described by Steve,

and thus the last statement
```
        return { PRODUCES[0]: pd.DataFrame(oc_list) }
```
does not get executed,

will that make the TaskManager realize that something happened from
```
 class AWSOccupancy(SourceProxy.SourceProxy):     def acquire(self):
```
and thus make the TaskManager not try to update the datablock with this null data?

Or I can update the code as follows;
```
        oc_list = [ i.data for i in occupancy_data ]
	if oc_list is null (empty)
	    return special object
        return { PRODUCES[0]: pd.DataFrame(oc_list) }
```
such that the TaskManager, when it receives this "special object" from calling 
```
class AWSOccupancy(): def acquire(self):
```
does not update the datablock with a null data..

I need to understand what happens inside TaskManager in terms of how it updates the datablock with the data returned from this acquire method.

**Comment by DmitryLitvintsev** [comment] 2020-06-12 14:20
I believe the problem is this:

"""
There is a source upstream of that which fails, but catches the exemption and returns a null datablock, """

so what is that module that swallows exception? If this module is found the exception needs to be raised/propagared to framework which sets the channel to ERROR state.

**Comment by hyunwoo18** [comment] 2020-06-25 01:24
I did a further investigation on this issue in my testing VM as follows:
First I simplified my DE configuration by having just one channel (AWS_Calculations_with_source_proxy)
with just 2 sources (AWSSpotPrice and AWSOccupancy) and 1 transform (AWSInstBurnRate).

And the next question was how to reproduce this error from AWS 
(EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.us-east-1.amazonaws.com/")

At first, I simply hard-wired a non-existent AWS region 
in decisionengine_modules/AWS/sources/AWSOccupancyWithSourceProxy.py
as follows

```
class AWSOccupancy(SourceProxy.SourceProxy):
    def acquire(self):
        temp_dict = {'CMS': { ('us-east-9) : ['m3.2xlarge']}}
	self.account_dict = temp_dict
```

But this did not exactly reproduce the problem reported because this wrong URL made only the initial run of sources fail (as can be seen in decisionengine/framework/taskmanager/TaskManager.py):

```
class TaskManager(object):
    def run(self):
       done_events = self.start_sources(  self.data_block_t0  )
       self.wait_for_all(done_events)
```

The original problem must have come from the following lines in the same file:

```
    def run(self):
        while self.get_state() == STEADY:
            try:
                self.wait_for_any(done_events)
                self.decision_cycle()
```

So, I had to revise false-region-generating code like the following:

```
class AWSOccupancy(SourceProxy.SourceProxy):
    def acquire(self):
........
	with open( '/tmp/hk.txt', 'r' ) as hkf:
            hkdata = hkf.read()

        temp_dict = {'CMS': { ('us-east-%s' % hkdata.rstrip() ) : ['m3.2xlarge'] } }
	self.account_dict = temp_dict
```

and once past the initial round of sources run, I updated /tmp/hk.txt to be 9.

And now I see the same error as reported:

```
2020-06-24 19:52:01,962 - root - TaskManager - 13949 - AWSOccupancy - ERROR - Exception running source AWSOccupancy : Could not connect to the endpoint URL: "https://ec2.us-east-9.amazonaws.com/"

EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.us-east-9.amazonaws.com/"
2020-06-24 19:52:02,324 - root - TaskManager - 13949 - MainThread - INFO - run_transforms
..........
2020-06-24 19:52:03,326 - root - TaskManager - 13949 - MainThread - INFO - all transforms finished
.......
2020-06-24 19:52:03,329 - root - TaskManager - 13949 - MainThread - INFO - ran all logic engines
2020-06-24 19:52:03,330 - root - TaskManager - 13949 - MainThread - INFO - Task Manager 0F16597C-2FA9-4DC6-AB6C-A5DD682E95B5 received stop signal and exits
2020-06-24 19:52:03,372 - root - TaskManager - 13949 - AWSSpotPrice - INFO - received stop_running signal for AWSSpotPrice
2020-06-24 19:52:03,376 - root - TaskManager - 13949 - AWSSpotPrice - INFO - stopped AWSSpotPrice
2020-06-24 19:52:08,345 - root - TaskManager - 13949 - AWSOccupancy - INFO - received stop_running signal for AWSOccupancy
2020-06-24 19:52:08,346 - root - TaskManager - 13949 - AWSOccupancy - INFO - stopped AWSOccupancy
2020-06-24 19:52:18,345 - root - TaskManager - 13949 - MainThread - ERROR - Error occured. Task Manager 0F16597C-2FA9-4DC6-AB6C-A5DD682E95B5 exits with state OFFLINE
```

And de-client command shows

```
$ de-client --status | grep state
channel: AWS_Calculations_with_source_proxy , id = 0, state = OFFLINE    
```

But I do not observe any failure of the following transform (AWSInstBurnRate) after this error,
i.e. the transform runs fine:

```
EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.us-east-9.amazonaws.com/"
2020-06-24 19:52:02,324 - root - TaskManager - 13949 - MainThread - INFO - run_transforms
2020-06-24 19:52:02,324 - root - TaskManager - 13949 - MainThread - INFO - starting transform AwsBurnRate
2020-06-24 19:52:02,324 - root - TaskManager - 13949 - AwsBurnRate - INFO - transform: AwsBurnRate expected keys: ['provisioner_resource_spot_prices', 'AWS_Occupancy'] provided keys: ['AWS_Occupancy', 'provisioner_resource_spot_prices']
2020-06-24 19:52:02,324 - root - TaskManager - 13949 - AwsBurnRate - INFO - run transform AwsBurnRate
2020-06-24 19:52:02,324 - root - TaskManager - 13949 - MainThread - INFO - Waiting for all tasks to run
2020-06-24 19:52:02,330 - root - TaskManager - 13949 - AwsBurnRate - INFO - transform put data
2020-06-24 19:52:03,326 - root - TaskManager - 13949 - MainThread - INFO - all transforms finished
```
Namely, expected keys and provided keys are identical.
And as can be seen in the log messages, the channel went OFFLINE..

Maybe I should repeat this same test in AWSBilling channel to see the index error in transform as Dmitry described above.

Anyway, with this channel (AWS_Calculations_with_source_proxy), when AWS endpoint error happens, the channel goes OFFLINE.
Isn't this what we want? 
Well, I will need to read this ticket description  more closely tomorrow..

**Comment by StevenCTimm** [comment] 2020-06-25 16:03
OK I realize that there is a problem above the way I described the issue.
Some of the failures in the AwsBurnRate transform have nothing to do with not being able to contact AWS, but rather in the fact that the factory_entries source in channel_aws_config_data channel failed, and there were no AWS factory entries listed and thus nothing for the AWSOccupancy source to query.  See for example the logs on hepcsvc03 at 2020-04-14 12:24

By contrast, when the 'Could not connect to the endpoint' error happens, as above, the transform appears to run ok but the channel goes offline.
(See hepcsvc03, AWS_Calculations_with_source_proxy.log.3, on 2020-01-21 09:22

**Comment by hyunwoo18** [comment] 2020-06-25 16:39
Steve,

As you pointed, I am looking in AWS_Calculations_with_source_proxy.log.1, 2020-04-14 12:24
which shows 

```
2020-04-14 12:24:22,076 - root - TaskManager - 6569 - AwsBurnRate - ERROR - exception from transform AwsBurnRate
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 384, in run_transform
    data = transform.worker.transform(data_block)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/AWS/transforms/AwsBurnRate.py", line 39, in transform
    on=["AccountName", "AvailabilityZone", "InstanceType"])
......skip
KeyError: 'AccountName'
```
My interpretation of this error is, AwsBurnRate transform in AWS_Calculations_with_source_proxy channel failed
because a key named AccountName was missing in either spot_prices or occupancy (shown in AWS/transform/AwsBurnRate.py). These datablocks spot_prices and occupancy are obviously produced in sources in the same channel (AWS_Calculations_with_source_proxy).

But I don't understand how this log messages match your new description which I quote here:
(Actually, I don't seem to understand the following statement of yours),

```
Some of the failures in the AwsBurnRate transform have nothing to do with not being able to contact AWS, 
but rather in the fact that the factory_entries source in channel_aws_config_data channel failed, 
and there were no AWS factory entries listed and thus nothing for the AWSOccupancy source to query.
```

So, this sentence seems to say, "factory_entries source in channel_aws_config_data channel fails, which causes no AWS factory entries to be listed (where?) and thus  nothing for the AWSOccupancy source to query and thus AwsBurnRate transform fails."
Is this what you meant?

How could an error from a source (factory_entries) in channel_aws_config_data channel affect a transform(AwsBurnRate) in another channel (AWS_Calculations_with_source_proxy)?

**Comment by StevenCTimm** [comment] 2020-06-25 16:52
Look at channel_aws_config_data.log at the same time frame

2020-04-14 12:23:06,537 - root - factory_entries - 16153 - FactoryEntries - WARNING - Query error fetching glidefactory classads from collector host(s) "cmssrv280.fnal.gov"
2020-04-14 12:23:06,538 - root - factory_entries - 16153 - FactoryEntries - ERROR - Query error fetching glidefactory classads from collector host(s) "cmssrv280.fnal.gov". Traceback: Traceback (most recent
 call last):
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/sources/factory_entries.py", line 66, in acquire
    condor_status.load(constraint, classad_attrs, self.condor_config)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/htcondor/htcondor_query.py", line 54, in load
    self.stored_data = self.fetch(constraint, format_list, condor_config)
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/htcondor/htcondor_query.py", line 184, in fetch
    classads = collector.query(adtype, constraint, attrs)
QueryError: Error querying pool cmssrv280.fnal.gov using python bindings: Failed communication with collector.

That source factory_entries produces the four data blocks Factory_Entries_AWS, Factory_Entries_GCE, Factory_Entries_Grid, and Factory_Entries_LCF

Factory_Entries_AWS is then CONSUMED by a transform gms_aws_config_data in the same channel_aws_config_data channel
which in turn produces aws_instance_limits and spot_occupancy_config

The AWSOccupancyWithSourceProxy.py in the AWS_Calculations_with_source_proxy.py depends on the info spot_occupancy_config (by fetching it from a source proxy).  If that is not there, it returns a blank block which does not have a key which then makes AWSInstBurnRate burp.

**Comment by hyunwoo18** [comment] 2020-06-25 20:29
Okay, Steve, thanks for the explanation.
Now I understand this data (spot_occupancy_config) flow from one channel (channel_aws_config_data) to another channel 
(AWS_Calculations_with_source_proxy).

Now, I am visiting again 2020-04-14 12:24 in hepcsvc03:AWS_Calculations_with_source_proxy.log.1
and see that when this happened, i.e. when the source factory_entries failed to produce Factory_Entries_AWS, 
AwsBurnRate eventually failed which eventually caused the channel (AWS_Calculations_with_source_proxy) itself to go OFFLINE.

So, what needs to be fixed for this phenomenon?
From what you and Dmitry said above, one of possible improvements is making the channel go OFFLINE rather than go unnoticed
but the log already seems to show that the channel go offline.

**Comment by StevenCTimm** [comment] 2020-06-26 21:27
The factory_entries source is already getting a bunch of retries thanks to work Shreyas is doing, so that should mitigate that part of the problem going forward.   Anything more fancy I think needs to be handled by the framework.


In the case of the AWS source failing to contact AWS that should take the channel offline.. as you said above it appears to do so,.

**Comment by StevenCTimm** [comment] 2020-10-22 15:15
This is now deployed in operations.  Closing

**Closed by StevenCTimm** 2020-10-22 15:15 UTC
Labels: ok_in_cirpm, operations
