### ISSUE TITLE
GCEBillingInfo : local variable 'CorrectedBillSummaryDict' referenced before assignment

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#209] opened 2020-04-22 20:01 UTC
Version 1.1.0-py27
2020-04-22 12:29:11,963 - root - GCEBillingInfo - 26936 - GCEBillingInfo - ERROR - not all arguments converted during string formatting
2020-04-22 12:29:11,963 - root - TaskManager - 26936 - GCEBillingInfo - ERROR - Exception running source GCEBillingInfo : local variable 'CorrectedBillSummaryDict' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 287, in run_source
    data = src.worker.acquire()
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/GCE/sources/GCEBillingInfo.py", line 459, in acquire
    return {PRODUCES[0]: pd.DataFrame([CorrectedBillSummaryDict])}
UnboundLocalError: local variable 'CorrectedBillSummaryDict' referenced before assignment

----

Some cosmetic changes were made to the routine GCEBillingInfo.py but it doesn't 
seem that it should have made CorrectedBillSummaryDict be undefined.

There may be some issues on this test node with the installation of the google libraries
or credentials on this sample node.  I am still investigating that.. but if so that exception should have been caught and flagged instead of dying at this stage of the code.

**Comment by StevenCTimm** [comment] 2020-04-22 21:59
By putting the version of GCEBillingInfo.py from decisionengine-standard-library 0.3.14  into the otherwise new installation the channel works.
All credentials are OK.

**Comment by DmitryLitvintsev** [comment] 2020-04-22 23:08
The issue is most likely to do with python 2 incompatible use of io.StringIO.

**Comment by StevenCTimm** [comment] 2020-04-23 14:54
RPM's made from Dmitry's latest pull request now have this GCEBillingInfo.py routine working correctly.

**Comment by StevenCTimm** [comment] 2020-04-24 22:09
Actually it's not working again.. the last test rpm that I installed on Wednesday evening,
and the formal 1.1.1 release rpm that I installed on Thursday, now both give the error:

2020-04-22 21:29:30,053 - root - GCEBillingInfo - 12807 - GCEBillingInfo - ERROR - Unable to download GCE billing file names because auth is not set up

I will have to investigate this further over the weekend.
Auth does appear to be set up.  All the credentials are fine and from the gsutil CLI with these same credentials I can list the bucket and download files from it.

**Comment by DmitryLitvintsev** [comment] 2020-04-24 22:15
Isn't it a different error ?

**Comment by StevenCTimm** [comment] 2020-04-24 22:17
Yes it's a different error than before.. but somehow the last commit broke something that was previously working and I didn't go back and check it until now--when I was looking at the logic engine complaining that the data block wasn't there.

**Comment by StevenCTimm** [comment] 2020-04-24 22:17
fermicloud155 and hepcsvc03 both in the state of error, you can log into either and look at them as you will.

**Comment by DmitryLitvintsev** [comment] 2020-04-24 22:20
here is the bit where it comes from:

``` 
      # URI scheme for Cloud Storage.
        GOOGLE_STORAGE = 'gs'
        LOCAL_FILE = 'file'

        # Access list of files from Goggle storage bucket
        try:
            uri = boto.storage_uri(self.bucketBillingName, GOOGLE_STORAGE)
            file_obj = uri.get_bucket()
        except NoAuthHandlerFound:
            self.logger.error(
                "Unable to download GCE billing file names because auth is not set up")
            return []
        except Exception:
            self.logger.error(
                "Able to auth but unable to download GCE billing files")
            return []
```

with 

```
self.bucketBillingName = 'billing-' + str(self.project_id)
```

**Comment by DmitryLitvintsev** [comment] 2020-04-24 22:21
Looks like real auth. error (unless it magically works if you revert `GCEBillingInfo.py` from old release)

**Comment by DmitryLitvintsev** [comment] 2020-04-24 23:59
@ fermicloud155 I have made two test programs 

GCEBillingInfo.py and GCEBillingInfo_new.py (first is "old" code second is "new"). Both fail the same:

```
[root@fermicloud155 ~]# python GCEBillingInfo.py
ERROR:logger:Unable to download GCE billing file names because auth is not set up
Empty DataFrame
Columns: []
Index: [0]


[root@fermicloud155 ~]# python GCEBillingInfo_new.py
ERROR:logger:Unable to download GCE billing file names because auth is not set up
Empty DataFrame
Columns: []
Index: [0]
[root@fermicloud155 ~]# 
```

**Comment by StevenCTimm** [comment] 2020-04-25 01:09
If the exception is not caught you get this trace:

>>> file_obj = uri.get_bucket()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/boto/storage_uri.py", line 181, in get_bucket
    conn = self.connect()
  File "/usr/lib/python2.7/site-packages/boto/storage_uri.py", line 140, in connect
    **connection_args)
  File "/usr/lib/python2.7/site-packages/boto/gs/connection.py", line 47, in __init__
    suppress_consec_slashes=suppress_consec_slashes)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.7/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 3 handlers were checked. ['OAuth2Auth', 'OAuth2ServiceAccountAuth', 'HmacAuthV1Handler'] Check your credentials

**Comment by DmitryLitvintsev** [comment] 2020-04-25 01:25
the fix seem to amount to the following:

This does to work:

```
import boto
GOOGLE_STORAGE = 'gs'
LOCAL_FILE = 'fiile'
uri = boto.storage_uri('billing-hepcloud-fnal', GOOGLE_STORAGE)
```
Whereas this works
```
import boto
import gcs_oauth2_boto_plugin

GOOGLE_STORAGE = 'gs'
uri = boto.storage_uri('billing-hepcloud-fnal', GOOGLE_STORAGE)
```

I removed the `import gcs_oauth2_boto_plugin` when pep speak complained.... 
I am making 1.1.2 release for decisionengine_modules

**Comment by StevenCTimm** [comment] 2020-04-25 02:14
ok 1.1.2 patched rpm is working on fermicloud155 and hepcsvc03. all the way jobs to glideins.

**Comment by DmitryLitvintsev** [comment] 2020-04-25 02:24
I am closing this issue

**Closed by DmitryLitvintsev** 2020-04-25 02:24 UTC
